apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgBVFzMK/C4vxwCMcF1DD5z8TEu17BH6QZhyKuKqrALkC1GKuzW243X8u24+iAT05VFsDGMYR1SU6t2KdeKR+UPF3cuyYW77LNGncMie5AXpo9ua6B+dUaeqn2+iFVMrREx8kShWyvE/E0WovGohXc3M/O4qUb9gUQ3oX6o08d2EgeuGjvrVaHP2H3ziFBt7R6iZtjti7zYd4UHHs29bJFZBfJVICjutQHbVWVd98/H4VQkGNkPsmD/1N9CxpfKRa3OWUiw3cRFvAPzjn1Jai6PT6ECtbNG3QcYrg6qld5gZwoRjYJoNhuPPzybd3VepfQxtU7kEzSY2kzLyPLWFlvpmqYL4qq5h8cbVzcnscn0g8StTviSO1cKMsIEQQ2hX+zVRUeEGULJ5If3TJkIjjaq5Ee2V6AaoSM1YpxiciGZWF/p+Yt6zh7IM44I8JBs3b8D9t+On5j8t4x/PZtmZPc+z/L6dQVeRt3NwIxxTNKaiYUEJtLjrBM8ZmC0pz3+chsvMWxJ+bGmWI0g7Vnf0GC7EkvupMUewjkj4pgOEnaC9MHf92JkfWUYjgwqViJZXCZJKEnuma/JhKrkHiCQUlGcKAfi+esAyRn/myEyPHnx5JGL/wN8SdUMMgfs6qHwKalG9Sqg3Ou3dLPvYUHp7aNBMnwIhoMWJVGZHGxPn5EdtNwzR28SvRpw7Li/3xT45m+8u7tDGJViCI30=
    user: AgCN6AbLyXKh+OeihmCv/DLfAq2SM18ovBl2QTJevxkA3zwcXTizJx8uUiEN9zGvjTVBMluaFR0L/QosesjdXVr1tLFoapjd8x8VeoXvq88BJ99LvAbsxE6cpzgCFERiDb7kq/f15d/Su2Lt4/rCy5422NxpbTkp82oGdvyxvkCU3wOt1czOdfIz2OCxTGRRVX1wwts9HmmncoAZ4jzJ5LVNbx6Yv7s+Tu1W9RdnRm939PdSC9TnXGfuUIosXU/NxDi48yl5JMNHq5+s4bofbEpJvzThPJ96SNiwaP8TqTrPeSp/3RPpMG2KE2SkVcn1o2dMTrdJlUNCwzDSwHSz2mWldIOZ1PD+c/YVnAIredJLs1vcuYw9uB/utNyh0Wt5GRG0a0ngU7P777jQiYarzq8amjgBOLxDTCqS2dD53t/yiPSRByP43F7nhP7qOEc9u6LtFrL07w9b8QCWDr3qIdKEJzIc4kF0Q3YgnTkgbugKrNMQ8MVP8IEQ7RLm6UfsvDZDw/GL1W+NWvxJFPcdOpc8DADtKUz6j7MAROFcH9in+c/Pk7BXcciS50SEv/Klp2PB4aZmtdeSKK+Brmom2ZP9w24UvpNaVhfMdhy6YeiPZtMuQIqf+wo047wpunfjEdi77XFb21OrhsY+Lw3xW2XH6bWx3YisXoaaCnmVnj6bC3g+Hs3ngjEu+EnSxTyvzyT3+3T7Og==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
